apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: springboot-k8s-svc
spec:
  selector:
    app: k8sAssignment
  ports:
    - protocol: "TCP"
      port: 8090 # The port that the service is running on in the cluster
      targetPort: 8090 # The port exposed by the service
  type: NodePort # type of the service.